// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FunctionOp } from "./FunctionOp";

export type FunctionConfig = { op: FunctionOp, param1: number, param2: number, };
