// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TopicBinding } from "./TopicBinding";
import type { TransitionConfig } from "./TransitionConfig";

export type StateMachineConfig = { states: Array<string>, initial: string, transitions: Array<TransitionConfig>, input_topics: Array<TopicBinding>, output_topics: Array<TopicBinding>, };
