// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Tmc2209StepperConfig = { uart_port: number, uart_addr: number, steps_per_rev: number, microsteps: number, };
