// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransitionAction } from "./TransitionAction";
import type { TransitionGuard } from "./TransitionGuard";

export type TransitionConfig = { from: string, to: string, guard: TransitionGuard, actions: Array<TransitionAction>, };
