// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldCondition } from "./FieldCondition";

export type TransitionGuard = { "type": "Topic", topic: string, condition: FieldCondition | null, } | { "type": "Unconditional" } | { "type": "GuardPort", port: number, };
