/** Dataflow graph types mirroring the Rust structures. */

import type {
  PlotConfig,
  UdpConfig,
  PubSubConfig,
  StateMachineConfig,
  AdcConfig,
  PwmConfig,
  GpioOutConfig,
  GpioInConfig,
  UartTxConfig,
  UartRxConfig,
  EncoderConfig,
  Ssd1306DisplayConfig,
  Tmc2209StepperConfig,
  Tmc2209StallGuardConfig,
} from '../../pkg/rustsim.js';

/** Config for constant block (data-driven, no Tsify export). */
export interface ConstantConfig { value: number }

/** Config for function blocks like gain/clamp (data-driven, no Tsify export). */
export interface FunctionConfig { [key: string]: unknown }

/** Maps block_type strings to their config types (generated by Tsify via wasm-pack). */
export interface BlockConfigMap {
  constant: ConstantConfig;
  gain: FunctionConfig;
  clamp: FunctionConfig;
  plot: PlotConfig;
  udp_source: UdpConfig;
  udp_sink: UdpConfig;
  adc_source: AdcConfig;
  pwm_sink: PwmConfig;
  gpio_out: GpioOutConfig;
  gpio_in: GpioInConfig;
  uart_tx: UartTxConfig;
  uart_rx: UartRxConfig;
  pubsub_source: PubSubConfig;
  pubsub_sink: PubSubConfig;
  state_machine: StateMachineConfig;
  encoder: EncoderConfig;
  ssd1306_display: Ssd1306DisplayConfig;
  tmc2209_stepper: Tmc2209StepperConfig;
  tmc2209_stallguard: Tmc2209StallGuardConfig;
}

export interface PortDef {
  name: string;
  kind: string; // "Float" | "Bytes" | "Text" | "Series" | "Any"
}

export interface ValueFloat { type: 'Float'; data: number }
export interface ValueBytes { type: 'Bytes'; data: number[] }
export interface ValueText { type: 'Text'; data: string }
export interface ValueSeries { type: 'Series'; data: number[] }
export type Value = ValueFloat | ValueBytes | ValueText | ValueSeries;

export interface ChannelSnapshot {
  id: number | { 0: number };
  from_block: number | { 0: number };
  from_port: number;
  to_block: number | { 0: number };
  to_port: number;
}

export interface BlockSnapshot {
  id: number;
  block_type: string;
  name: string;
  inputs: PortDef[];
  outputs: PortDef[];
  config: Record<string, unknown>;
  output_values: (Value | null)[];
}

export interface GraphSnapshot {
  blocks: BlockSnapshot[];
  channels: ChannelSnapshot[];
  tick_count: number;
  time: number;
}

export interface BlockTypeInfo {
  block_type: string;
  name: string;
  category: string;
}

/** UI-only position data for the node editor. */
export interface NodePosition {
  x: number;
  y: number;
}
