//! Deployment manifest — the "Linker" between control logic IR and hardware.
//!
//! # Layers
//!
//! 1. **System Topology** ([`SystemTopology`]) — nodes (MCU instances) and
//!    physical links between them.
//! 2. **Task Bindings** ([`TaskBinding`]) — which sub-graphs run on which
//!    node, at what frequency/trigger, and at what priority.
//! 3. **Channel Bindings** ([`ChannelBinding`]) — logical signal names mapped
//!    to intra-node memory channels or inter-node pub/sub over a physical link.
//! 4. **Peripheral Bindings** ([`PeripheralBinding`]) — a block's logical port
//!    mapped to a specific MCU peripheral instance and pins.
//!
//! The frontend produces this manifest; the code generator or runtime
//! simulation consumes it to instantiate Embassy tasks and wire channels.

use alloc::string::String;
use alloc::vec::Vec;

use serde::{Deserialize, Serialize};

// ---------------------------------------------------------------------------
// Top-level manifest
// ---------------------------------------------------------------------------

/// Complete deployment manifest.
///
/// This is the bridge between the dataflow IR and the physical hardware.
/// Generated by the frontend, consumed by codegen and the runtime simulator.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeploymentManifest {
    /// System topology — nodes and physical links.
    pub topology: SystemTopology,
    /// Task bindings — sub-graphs assigned to nodes with scheduling.
    pub tasks: Vec<TaskBinding>,
    /// Channel bindings — logical signals mapped to transport.
    pub channels: Vec<ChannelBinding>,
    /// Peripheral bindings — block ports mapped to MCU peripherals + pins.
    pub peripheral_bindings: Vec<PeripheralBinding>,
}

// ---------------------------------------------------------------------------
// Layer 1: System Topology
// ---------------------------------------------------------------------------

/// A set of MCU nodes and the physical links between them.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SystemTopology {
    /// Board nodes — each an MCU instance.
    pub nodes: Vec<BoardNode>,
    /// Physical wiring between nodes.
    pub links: Vec<PhysicalLink>,
}

/// An MCU node in the system.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BoardNode {
    /// Unique node identifier (e.g., "motor_controller", "sensor_hub").
    pub id: String,
    /// MCU family (matches [`crate::inventory::McuDef::family`]).
    pub mcu_family: String,
    /// Board name or PCB revision (optional, informational).
    pub board: Option<String>,
    /// Embassy target triple for this node (e.g., "thumbv7em-none-eabihf").
    pub rust_target: Option<String>,
}

/// A physical link between two nodes.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PhysicalLink {
    /// Link identifier (e.g., "can_bus_1", "spi_link_ab").
    pub id: String,
    /// Source node.
    pub from_node: String,
    /// Source peripheral instance on that node (e.g., "FDCAN1", "SPI1").
    pub from_peripheral: String,
    /// Destination node.
    pub to_node: String,
    /// Destination peripheral instance (e.g., "FDCAN1", "SPI2").
    pub to_peripheral: String,
    /// Transport protocol.
    pub transport: Transport,
}

/// Transport protocol for an inter-node link.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Transport {
    Can,
    Rs485,
    Spi,
    Uart,
    I2c,
    Ethernet,
    Wifi,
    SharedMemory,
}

// ---------------------------------------------------------------------------
// Layer 2: Task Bindings
// ---------------------------------------------------------------------------

/// A task binding: a sub-graph assigned to a node with scheduling info.
///
/// Each task becomes an `#[embassy_executor::task]` in generated code.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaskBinding {
    /// Task name (e.g., "pid_loop", "sensor_read").
    pub name: String,
    /// Which node runs this task (references [`BoardNode::id`]).
    pub node: String,
    /// Block IDs that belong to this task's sub-graph.
    pub blocks: Vec<u32>,
    /// How this task is triggered.
    pub trigger: TaskTrigger,
    /// Task priority (lower number = higher priority).
    pub priority: u8,
    /// Stack size in bytes (for Embassy task spawning).
    pub stack_size: Option<u32>,
}

/// How a task is triggered / scheduled.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum TaskTrigger {
    /// Periodic timer tick.
    Periodic {
        /// Tick frequency in Hz.
        hz: f64,
    },
    /// Hardware interrupt (reactive).
    Interrupt {
        /// IRQ name (matches [`crate::inventory::InterruptDef::name`]).
        irq: String,
    },
    /// Triggered by a channel message (event-driven).
    Event {
        /// Logical channel name that triggers this task.
        channel: String,
    },
    /// One-shot: runs once at startup.
    Init,
}

// ---------------------------------------------------------------------------
// Layer 3: Channel Bindings
// ---------------------------------------------------------------------------

/// A logical signal mapped to a physical transport.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChannelBinding {
    /// Logical channel name (e.g., "Motor_Torque_Cmd").
    pub name: String,
    /// Source task.
    pub from_task: String,
    /// Source block port (block_id, port_index).
    pub from_port: (u32, usize),
    /// Destination task.
    pub to_task: String,
    /// Destination block port (block_id, port_index).
    pub to_port: (u32, usize),
    /// How this channel is physically realized.
    pub transport: ChannelTransport,
}

/// Physical realization of a logical channel.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ChannelTransport {
    /// Same MCU: `embassy_sync::channel::Channel` in memory.
    IntraNode {
        /// Buffer depth for the channel (number of queued values).
        depth: u16,
    },
    /// Cross-MCU: pub/sub over a physical link.
    InterNode {
        /// Physical link ID (references [`PhysicalLink::id`]).
        link: String,
        /// Topic name on the transport bus.
        topic: String,
        /// Serialization format for the message.
        encoding: Encoding,
    },
    /// Host simulation: direct value pass.
    Simulated,
}

/// Wire encoding for inter-node channels.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Encoding {
    /// Raw f64 (8 bytes, native endian).
    RawF64,
    /// CAN-style: packed into 8-byte frame.
    CanFrame,
    /// COBS-encoded binary.
    Cobs,
    /// Postcard (serde, no_std friendly).
    Postcard,
}

// ---------------------------------------------------------------------------
// Layer 4: Peripheral Bindings
// ---------------------------------------------------------------------------

/// A block's logical port mapped to a specific MCU peripheral and pins.
///
/// This replaces the manual "glue code" of Embedded Coder — the code
/// generator reads these bindings to produce the correct Embassy
/// peripheral initialization and handle passing.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PeripheralBinding {
    /// Block ID in the dataflow graph.
    pub block_id: u32,
    /// Block's logical port name (e.g., "Sensor_In", "PWM_Out").
    pub port_name: String,
    /// Target node (references [`BoardNode::id`]).
    pub node: String,
    /// MCU peripheral instance (e.g., "I2C1", "ADC1").
    pub peripheral: String,
    /// Pin assignments for this binding.
    pub pins: Vec<PinBinding>,
    /// DMA channel to use (if any).
    pub dma: Option<String>,
    /// Additional config (peripheral-specific).
    pub config: PeripheralConfig,
}

/// A pin assignment within a peripheral binding.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PinBinding {
    /// Signal name (e.g., "TX", "SDA", "CH1").
    pub signal: String,
    /// Physical pin (e.g., "PA9", "GP0").
    pub pin: String,
    /// Alternate function (if applicable).
    pub af: Option<u8>,
}

/// Peripheral-specific configuration.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum PeripheralConfig {
    Adc {
        /// Hardware channel on the ADC peripheral.
        channel: u8,
        /// Resolution in bits (8, 10, 12, 16).
        resolution_bits: u8,
        /// Sample time index (MCU-specific).
        sample_time: u8,
    },
    Pwm {
        /// PWM frequency in Hz.
        frequency_hz: u32,
        /// Dead-time in nanoseconds (for complementary outputs).
        dead_time_ns: Option<u32>,
    },
    Uart {
        /// Baud rate.
        baud: u32,
        /// Word length (7, 8, 9).
        word_bits: u8,
        /// Parity.
        parity: Parity,
        /// Stop bits (1 or 2).
        stop_bits: u8,
    },
    Spi {
        /// Clock frequency in Hz.
        frequency_hz: u32,
        /// SPI mode (0–3).
        mode: u8,
        /// Bit order.
        bit_order: BitOrder,
    },
    I2c {
        /// I2C bus speed.
        speed: I2cSpeed,
        /// Target device address (7-bit).
        address: u8,
    },
    Gpio {
        /// Pull resistor configuration.
        pull: GpioPull,
    },
    Encoder {
        /// Counts per revolution.
        counts_per_rev: u32,
    },
    Can {
        /// Nominal bitrate.
        bitrate: u32,
        /// Data bitrate (for FD-CAN).
        fd_bitrate: Option<u32>,
    },
    Timer {
        /// Timer frequency (auto-reload value calculation).
        frequency_hz: u32,
    },
    /// No additional config needed.
    None,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Parity {
    None,
    Even,
    Odd,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum BitOrder {
    MsbFirst,
    LsbFirst,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum I2cSpeed {
    /// 100 kHz.
    Standard,
    /// 400 kHz.
    Fast,
    /// 1 MHz.
    FastPlus,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum GpioPull {
    None,
    Up,
    Down,
}

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

/// Validate a deployment manifest for internal consistency.
pub fn validate_manifest(manifest: &DeploymentManifest) -> Result<(), Vec<String>> {
    let mut errors = Vec::new();

    let node_ids: Vec<&str> = manifest
        .topology
        .nodes
        .iter()
        .map(|n| n.id.as_str())
        .collect();

    // Every task must reference a valid node
    for task in &manifest.tasks {
        if !node_ids.contains(&task.node.as_str()) {
            errors.push(alloc::format!(
                "task '{}' references unknown node '{}'",
                task.name,
                task.node
            ));
        }
    }

    // Every channel must reference valid tasks
    let task_names: Vec<&str> = manifest.tasks.iter().map(|t| t.name.as_str()).collect();
    for ch in &manifest.channels {
        if !task_names.contains(&ch.from_task.as_str()) {
            errors.push(alloc::format!(
                "channel '{}' references unknown source task '{}'",
                ch.name,
                ch.from_task
            ));
        }
        if !task_names.contains(&ch.to_task.as_str()) {
            errors.push(alloc::format!(
                "channel '{}' references unknown dest task '{}'",
                ch.name,
                ch.to_task
            ));
        }
    }

    // Inter-node channels must reference valid links
    for ch in &manifest.channels {
        if let ChannelTransport::InterNode { ref link, .. } = ch.transport {
            if !manifest.topology.links.iter().any(|l| l.id == *link) {
                errors.push(alloc::format!(
                    "channel '{}' references unknown link '{}'",
                    ch.name,
                    link
                ));
            }
        }
    }

    // Every peripheral binding must reference a valid node
    for pb in &manifest.peripheral_bindings {
        if !node_ids.contains(&pb.node.as_str()) {
            errors.push(alloc::format!(
                "peripheral binding for block {} references unknown node '{}'",
                pb.block_id,
                pb.node
            ));
        }
    }

    // Every block should appear in exactly one task
    let mut all_blocks: Vec<u32> = manifest
        .tasks
        .iter()
        .flat_map(|t| t.blocks.iter().copied())
        .collect();
    all_blocks.sort();
    for i in 1..all_blocks.len() {
        if all_blocks[i] == all_blocks[i - 1] {
            errors.push(alloc::format!(
                "block {} is assigned to multiple tasks",
                all_blocks[i]
            ));
        }
    }

    // Physical links must reference valid nodes
    for link in &manifest.topology.links {
        if !node_ids.contains(&link.from_node.as_str()) {
            errors.push(alloc::format!(
                "link '{}' references unknown source node '{}'",
                link.id,
                link.from_node
            ));
        }
        if !node_ids.contains(&link.to_node.as_str()) {
            errors.push(alloc::format!(
                "link '{}' references unknown dest node '{}'",
                link.id,
                link.to_node
            ));
        }
    }

    if errors.is_empty() {
        Ok(())
    } else {
        Err(errors)
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    extern crate std;

    fn example_manifest() -> DeploymentManifest {
        DeploymentManifest {
            topology: SystemTopology {
                nodes: alloc::vec![
                    BoardNode {
                        id: s("flight_ctrl"),
                        mcu_family: s("Stm32f4"),
                        board: Some(s("FC_V2")),
                        rust_target: Some(s("thumbv7em-none-eabihf")),
                    },
                    BoardNode {
                        id: s("sensor_hub"),
                        mcu_family: s("Esp32c3"),
                        board: None,
                        rust_target: Some(s("riscv32imc-unknown-none-elf")),
                    },
                ],
                links: alloc::vec![PhysicalLink {
                    id: s("can_bus_1"),
                    from_node: s("flight_ctrl"),
                    from_peripheral: s("FDCAN1"),
                    to_node: s("sensor_hub"),
                    to_peripheral: s("TWAI0"),
                    transport: Transport::Can,
                },],
            },
            tasks: alloc::vec![
                TaskBinding {
                    name: s("pid_loop"),
                    node: s("flight_ctrl"),
                    blocks: alloc::vec![1, 2, 3],
                    trigger: TaskTrigger::Periodic { hz: 1000.0 },
                    priority: 1,
                    stack_size: Some(4096),
                },
                TaskBinding {
                    name: s("sensor_read"),
                    node: s("sensor_hub"),
                    blocks: alloc::vec![4, 5],
                    trigger: TaskTrigger::Periodic { hz: 100.0 },
                    priority: 2,
                    stack_size: None,
                },
            ],
            channels: alloc::vec![
                ChannelBinding {
                    name: s("Motor_Torque_Cmd"),
                    from_task: s("pid_loop"),
                    from_port: (3, 0),
                    to_task: s("pid_loop"),
                    to_port: (2, 0),
                    transport: ChannelTransport::IntraNode { depth: 4 },
                },
                ChannelBinding {
                    name: s("Sensor_Data"),
                    from_task: s("sensor_read"),
                    from_port: (5, 0),
                    to_task: s("pid_loop"),
                    to_port: (1, 0),
                    transport: ChannelTransport::InterNode {
                        link: s("can_bus_1"),
                        topic: s("sensor_data"),
                        encoding: Encoding::CanFrame,
                    },
                },
            ],
            peripheral_bindings: alloc::vec![PeripheralBinding {
                block_id: 2,
                port_name: s("PWM_Out"),
                node: s("flight_ctrl"),
                peripheral: s("TIM1"),
                pins: alloc::vec![PinBinding {
                    signal: s("CH1"),
                    pin: s("PA8"),
                    af: Some(1),
                }],
                dma: None,
                config: PeripheralConfig::Pwm {
                    frequency_hz: 20_000,
                    dead_time_ns: None,
                },
            },],
        }
    }

    fn s(v: &str) -> String {
        String::from(v)
    }

    #[test]
    fn validate_valid_manifest() {
        let m = example_manifest();
        assert!(validate_manifest(&m).is_ok());
    }

    #[test]
    fn validate_unknown_node_in_task() {
        let mut m = example_manifest();
        m.tasks[0].node = s("unknown_node");
        let errs = validate_manifest(&m).unwrap_err();
        assert!(errs.iter().any(|e| e.contains("unknown node")));
    }

    #[test]
    fn validate_unknown_task_in_channel() {
        let mut m = example_manifest();
        m.channels[0].from_task = s("nonexistent");
        let errs = validate_manifest(&m).unwrap_err();
        assert!(errs.iter().any(|e| e.contains("unknown source task")));
    }

    #[test]
    fn validate_unknown_link_in_channel() {
        let mut m = example_manifest();
        m.channels[1] = ChannelBinding {
            name: s("bad"),
            from_task: s("sensor_read"),
            from_port: (5, 0),
            to_task: s("pid_loop"),
            to_port: (1, 0),
            transport: ChannelTransport::InterNode {
                link: s("nonexistent_link"),
                topic: s("x"),
                encoding: Encoding::RawF64,
            },
        };
        let errs = validate_manifest(&m).unwrap_err();
        assert!(errs.iter().any(|e| e.contains("unknown link")));
    }

    #[test]
    fn validate_duplicate_block_assignment() {
        let mut m = example_manifest();
        // Block 3 in both tasks
        m.tasks[1].blocks.push(3);
        let errs = validate_manifest(&m).unwrap_err();
        assert!(errs.iter().any(|e| e.contains("multiple tasks")));
    }

    #[test]
    fn serde_roundtrip_manifest() {
        let m = example_manifest();
        let json = serde_json::to_string_pretty(&m).unwrap();
        let parsed: DeploymentManifest = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.topology.nodes.len(), 2);
        assert_eq!(parsed.tasks.len(), 2);
        assert_eq!(parsed.channels.len(), 2);
        assert_eq!(parsed.peripheral_bindings.len(), 1);
    }

    #[test]
    fn serde_task_trigger_variants() {
        let triggers = alloc::vec![
            TaskTrigger::Periodic { hz: 1000.0 },
            TaskTrigger::Interrupt { irq: s("USART1") },
            TaskTrigger::Event {
                channel: s("Motor_Cmd")
            },
            TaskTrigger::Init,
        ];
        for t in triggers {
            let json = serde_json::to_string(&t).unwrap();
            let _: TaskTrigger = serde_json::from_str(&json).unwrap();
        }
    }

    #[test]
    fn serde_peripheral_config_variants() {
        let configs = alloc::vec![
            PeripheralConfig::Adc {
                channel: 0,
                resolution_bits: 12,
                sample_time: 3
            },
            PeripheralConfig::Pwm {
                frequency_hz: 20_000,
                dead_time_ns: Some(100)
            },
            PeripheralConfig::Uart {
                baud: 115200,
                word_bits: 8,
                parity: Parity::None,
                stop_bits: 1
            },
            PeripheralConfig::Spi {
                frequency_hz: 1_000_000,
                mode: 0,
                bit_order: BitOrder::MsbFirst
            },
            PeripheralConfig::I2c {
                speed: I2cSpeed::Fast,
                address: 0x3C
            },
            PeripheralConfig::Gpio { pull: GpioPull::Up },
            PeripheralConfig::Encoder {
                counts_per_rev: 4096
            },
            PeripheralConfig::Can {
                bitrate: 500_000,
                fd_bitrate: Some(2_000_000)
            },
            PeripheralConfig::Timer {
                frequency_hz: 10_000
            },
            PeripheralConfig::None,
        ];
        for c in configs {
            let json = serde_json::to_string(&c).unwrap();
            let _: PeripheralConfig = serde_json::from_str(&json).unwrap();
        }
    }

    #[test]
    fn validate_bad_link_node_ref() {
        let mut m = example_manifest();
        m.topology.links[0].from_node = s("ghost");
        let errs = validate_manifest(&m).unwrap_err();
        assert!(errs.iter().any(|e| e.contains("unknown source node")));
    }
}
